"""Markdown digest rendering. Pure function of the Report; scraped text is shown as data.

Every item carries its details inline (what happened, to whom, who did it and how they
operate) so the digest reads on its own; reference links stay as a backup only.
"""

from __future__ import annotations

from daily_darkweb.core.models import (
    Alert,
    CollectionStatus,
    CountDelta,
    GroupProfile,
    Report,
    Trends,
)
from daily_darkweb.core.trends import DUE_SOON_DAYS, RANSOMWARE_SOURCE
from daily_darkweb.interface.digest_view import (
    AI_NOTES_DISCLAIMER,
    AI_NOTES_TITLE,
    PROFILES_NOTE,
    PROFILES_TITLE,
    SNIPPET_LIMIT,
    TOP_OBSERVATIONS,
    build_view,
    defense_tactics,
    detail_lines,
    exploited_cve_lines,
    format_delta,
    history_note,
    infostealer_note,
    item_description,
    profile_facts,
    profiles_by_group,
    tactic_line,
    tool_lines,
    victim_context,
)


def render_markdown(report: Report) -> str:
    view = build_view(report)
    profiled = profiles_by_group(report)
    lines: list[str] = [f"# Daily Darkweb digest — {report.generated_at:%Y-%m-%d %H:%M} UTC", ""]

    lines.append("## Collector status")
    for result in report.collector_results:
        if result.status is CollectionStatus.OK:
            lines.append(f"- `{result.source}`: OK ({len(result.items)} items)")
        else:
            lines.append(
                f"- `{result.source}`: **FAILED — could not determine, do not treat as "
                f"all-clear** ({result.error})"
            )
    lines.append("")

    lines.extend(_render_notes(report))
    if report.trends:
        lines.extend(_render_trends(report.trends))

    lines.append(f"## Watchlist alerts ({len(view.alerts)})")
    if view.alerts:
        for alert in view.alerts:
            lines.extend(_render_alert(alert, profiled))
    else:
        lines.append("No watchlist matches in new signals.")
    lines.append("")

    lines.append(f"## Vulnerability watch ({len(view.vulnerability_watch)})")
    lines.append("Every new confirmed-exploited CVE from CISA KEV, beyond your watchlist.")
    if view.vulnerability_watch:
        for alert in view.vulnerability_watch:
            lines.extend(_render_alert(alert, profiled))
    else:
        lines.append("No additional exploited CVEs outside your watchlist this run.")
    lines.append("")

    lines.append("## Threat landscape (ransomware, new signals)")
    if view.landscape_observations:
        lines.append(f"- New signals: {view.landscape_total}")
        lines.append(f"- Most active groups: {_top(view.top_actors)}")
        lines.append(f"- Most hit sectors: {_top(view.top_sectors)}")
        lines.append(f"- Most hit countries: {_top(view.top_countries)}")
        lines.append("")
        lines.append(f"### Latest observations (top {TOP_OBSERVATIONS})")
        for obs in view.landscape_observations[:TOP_OBSERVATIONS]:
            context = ", ".join(x for x in (obs.item.sector, obs.item.country) if x)
            suffix = f" ({context})" if context else ""
            _, description = item_description(obs.item, SNIPPET_LIMIT)
            snippet = f" — {description}" if description else ""
            lines.append(f"- [{obs.severity.value}] {obs.item.title}{suffix}{snippet}")
    else:
        lines.append("No new signals since last run.")
    lines.append("")

    lines.extend(_render_profiles(report))
    return "\n".join(lines)


def _render_alert(alert: Alert, profiled: dict[str, GroupProfile]) -> list[str]:
    item = alert.item
    matched = ", ".join(f"{m.field.value}={m.watch_value}" for m in alert.matches)
    lines = [f"### [{alert.severity.value.upper()} {alert.score}] {item.title}"]
    if matched:
        lines.append(f"- Matched: {matched}")
    published = f"{item.published_at:%Y-%m-%d %H:%M} UTC" if item.published_at else "unknown"
    lines.append(f"- Source: `{item.source}` | published: {published}")
    if item.source == RANSOMWARE_SOURCE:
        context = victim_context(item)
        if context:
            lines.append(f"- Victim: {context}")
        source_ai, description = item_description(item)
        if description:
            label = (
                "Description (AI-generated by the source)"
                if source_ai
                else "Description (unverified)"
            )
            lines.append(f"- {label}: {description}")
        if item.actor:
            known = item.actor.lower() in profiled
            lines.append(f"- Group: {item.actor}" + (" — profile below" if known else ""))
        exposure = infostealer_note(item)
        if exposure:
            lines.append(f"- Infostealer exposure: {exposure}")
    else:
        lines.extend(f"- {line}" for line in detail_lines(item))
    if item.due_date:
        lines.append(f"- Patch by: {item.due_date:%Y-%m-%d}")
    if item.press_url:
        lines.append(f"- Press coverage (backup link): {item.press_url}")
    if item.reference_url:
        lines.append(f"- Reference (backup link): {item.reference_url}")
    lines.append("")
    return lines


def _render_profiles(report: Report) -> list[str]:
    if not report.group_profiles and not report.profile_errors:
        return []
    lines = [f"## {PROFILES_TITLE} ({len(report.group_profiles)})", PROFILES_NOTE, ""]
    for profile in report.group_profiles:
        lines.append(f"### {profile.name}")
        facts = profile_facts(profile)
        if facts:
            lines.append(f"_{'; '.join(facts)}_")
        if profile.description:
            lines.append(profile.description)
        tactics = defense_tactics(profile)
        initial = [t for t in tactics if t.name.lower() == "initial access"]
        for tactic in initial:
            lines.append("- How they get in (Initial Access):")
            for t in tactic.techniques:
                details = f": {t.details}" if t.details else ""
                lines.append(f"  - {t.name} ({t.technique_id}){details}")
        cves = exploited_cve_lines(profile)
        if cves:
            lines.append("- Vulnerabilities they exploit (highest CVSS first):")
            lines.extend(f"  - {cve}" for cve in cves)
        lines.extend(f"- {tactic_line(t)}" for t in tactics if t.name.lower() != "initial access")
        if not tactics:
            lines.append("- No ATT&CK technique mapping published for this group yet.")
        tools = tool_lines(profile)
        if tools:
            lines.append(f"- Tools: {'; '.join(tools)}")
        if profile.reference_url:
            lines.append(f"- Reference (backup link): {profile.reference_url}")
        lines.append("")
    if report.profile_errors:
        lines.extend([f"Profiles unavailable: {', '.join(report.profile_errors)}.", ""])
    return lines


def _render_notes(report: Report) -> list[str]:
    if report.analyst_notes is None and report.analyst_notes_unavailable is None:
        return []
    lines = [f"## {AI_NOTES_TITLE} (AI generated)", f"_{AI_NOTES_DISCLAIMER}_", ""]
    notes = report.analyst_notes
    if notes is None:
        lines.extend([f"Unavailable for this run: {report.analyst_notes_unavailable}.", ""])
        return lines
    lines.append(f"**{notes.headline}**")
    lines.extend(f"- {point}" for point in notes.points)
    for heading, entries in (("Recommended actions", notes.actions), ("Caveats", notes.caveats)):
        if entries:
            lines.extend(["", f"{heading}:"])
            lines.extend(f"- {entry}" for entry in entries)
    lines.append("")
    return lines


def _render_trends(trends: Trends) -> list[str]:
    lines = [
        f"## Trends (last {trends.window_days} days)",
        f"- Ransomware claims: {format_delta(trends.ransomware_claims)}",
        f"- Most active groups: {_deltas(trends.top_groups)}",
    ]
    if trends.new_groups:
        lines.append(f"- New groups this window: {', '.join(trends.new_groups)}")
    lines.append(f"- Most hit sectors: {_deltas(trends.top_sectors)}")
    lines.append(f"- Most hit countries: {_deltas(trends.top_countries)}")
    watch = f"- Watchlist countries: {format_delta(trends.watch_countries)}"
    if trends.watch_country_breakdown:
        watch += f" — {_deltas(trends.watch_country_breakdown)}"
    lines.append(watch)
    lines.append(f"- CISA KEV additions: {format_delta(trends.kev_added)}")
    if trends.kev_due_soon:
        due = ", ".join(f"{e.cve_id} (due {e.due_date})" for e in trends.kev_due_soon)
        lines.append(f"- KEV deadlines in the next {DUE_SOON_DAYS} days: {due}")
    lines.extend([f"- {history_note(trends)}", ""])
    return lines


def _deltas(deltas: list[CountDelta]) -> str:
    if not deltas:
        return "n/a"
    return ", ".join(f"{d.name} {format_delta(d)}" for d in deltas)


def _top(pairs: list[tuple[str, int]]) -> str:
    if not pairs:
        return "n/a"
    return ", ".join(f"{name} ({count})" for name, count in pairs)
